<a href="https://colab.research.google.com/github/LAC1012/Portable-Info-Structure/blob/main/I3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [ ]:
url = "https://www.washington.edu/students/crscat/imt.html"

response = requests.get(url)
print(response.status_code)
print(response.text[:100])

200
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">


<html>

In [ ]:
soup = BeautifulSoup(response.text,"html.parser")
print(soup.get_text("\n")[:20000])

INFORMATION MANAGEMENT & TECHNOLOGY














Search
 |

Directories
 |

Reference
    Tools










UW Home
 >
Discover UW
 >
Student Guide




	UW Bothell Course Descriptions



	UW Tacoma Course Descriptions



	Glossary





THE INFORMATION SCHOOL

THE INFORMATION SCHOOL

INFORMATION MANAGEMENT & TECHNOLOGY



Detailed course offerings (Time Schedule) are available for


Spring Quarter 2026:
Time Schedule (NetID required)
 |
Course Offerings


Summer Quarter 2026:
Time Schedule (NetID required)
 |
Course Offerings


Autumn Quarter 2026:
Time Schedule (NetID required)
 |
Course Offerings




IMT 500 Foundations of Information Management (4)
Examines the role and function of information and information management in individual, organizational, community, and social contexts. Topics include defining information and information management concepts; overview of systems and systems architecture, methods of managing information and information flows within organizations; and internal and external communication in professional settings.
View course details in MyPlan: IMT 500


IMT 511 Introduction to Programming for Information and Data Science (4)
Introduces fundamentals of computer programming as used for data science. Covers foundational skills necessary for writing stand-alone computer scripts, including programming syntax, data structuring, and procedural definition (functions). Includes programming tools and environments (e.g., command-line). Emphasizes skills in language syntax, debugging, algorithmic thinking, and data comprehension. Assumes no previous programming background. Course equivalent to: LIS 511.
View course details in MyPlan: IMT 511


IMT 519 Information Science Study Abroad (1-8, max. 18)
International seminar, led by Information School faculty or researchers. Each addresses a specialized area of information studies. Topics vary. Some seminars may require language proficiency. See the UW Study Abroad website for information on specific offerings in any given year. Course equivalent to: LIS 519.
View course details in MyPlan: IMT 519


IMT 526 Building and Applying Large Language Models (4)
Introduces the building blocks of large language models (LLMs) using theories and practice. Primarily covers foundational models and technical elements of LLMs through hands-on exercises and problems, while also covering the potential social impacts of particular technical decisions and approaches. Prerequisite: IMT 573 and IMT 574.
View course details in MyPlan: IMT 526


IMT 530 Organization of Information Resources (4)
Introduction to issues in organization of information and information objects including analysis of intellectual and physical characteristics of information objects; use of metadata and metadata standards for information systems; theory of classification, including semantic relationships and facet analysis; creation of controlled vocabularies; and display and arrangement.
View course details in MyPlan: IMT 530


IMT 535 Introduction to Information Architecture (5)
Introduces concepts and methods of front- and back-end information architecture. Covers back-end topics including data and content modeling, taxonomy, controlled vocabulary, SEO, search, and analytics. Covers front-end topics including design thinking, design process, design patterns, navigation, workflow, labeling, orientation, and information scent. Unifies front- and back-end IA.
View course details in MyPlan: IMT 535


IMT 540 Design Methods for Interactive Systems (4)
Introduction to the theory and practice of user-centered design. Examines design methods for identifying and describing user needs, specifying and prototyping new systems, and evaluating the usability of systems. Examines design methodologies such as contextual design and value-sensitive design, giving specific emphasis to human-information interaction. Prerequisite: permission of instructor.
View course details in MyPlan: IMT 540


IMT 541 Enterprise Information Systems Analysis and Design (4)
Uses Systems Development Lifecycle (SDLC) as a methodology for addressing complex enterprise information systems problems. Through each phase of SDLC, students engage in current and future state analysis and design activities, including, project identification, selection and initiation, baseline project planning, feasibility and risk analysis, requirements gathering and structuring, system development, implementation, and maintenance strategies.
View course details in MyPlan: IMT 541


IMT 542 Portable Information Structures (4)
Introduces the concepts and methods used to analyze, store, manage, and present information and navigation. Equal weight given to understanding structures and implementing them. Topics covered include information analysis and organizational methods as well as markup standards (e.g., JSON, XML) and metadata concepts and application.
View course details in MyPlan: IMT 542


IMT 543 Relational Database Management Systems (4)
Introduces relational database design, implementation, and management, with a focus on using relational database management systems (DBMS) to manage data in an organization. Topics include: data modeling tools and techniques, conceptual and logical database design, physical implementation, SQL, data management, and database administration. Course equivalent to: LIS 543.
View course details in MyPlan: IMT 543


IMT 546 Data Communications and Networking (4)
Covers local and wide-area computer networking including topologies and hardware, packet switching, client/server architectures, network protocols, and network servers and applications. Also addresses server operating systems, management, security, authentication, and policy issues associated with distributed networks.
View course details in MyPlan: IMT 546


IMT 547 Social Media Data Mining and Analysis (4)
Explores techniques for collecting and analyzing social media. Students gain direct experience with methods for collecting a social media corpus, defining features of activity that are relevant for analysis, and analyzing those features.
View course details in MyPlan: IMT 547


IMT 550 Policy and Ethics in Information Management (4)
Explores a range of information issues in the social and organizational context of information professionals, including professional ethics, privacy, freedom of expression, and intellectual property. Gives students tools for analysis of the kinds of social and ethical issues that will arise in their future lives as information professionals.
View course details in MyPlan: IMT 550


IMT 555 Foundations of Cybersecurity (4)
Examines information security challenges and solutions, which information management professionals contend with when providing technology services and applications based on premises and cloud platforms. Students solidify the terminology and security architecture via hands-on labs using open source and cloud-based tools. Security topics selected from industry-standard frameworks.
View course details in MyPlan: IMT 555


IMT 558 Leading and Managing Enterprise Information Security (4)
Examines the elements of managing and leading enterprise information security programs from a leadership perspective. Students review real world scenarios and explore challenges facing information security leaders. Develop an information security plan and program that meets the culture and goals of a company to address the challenging threat environment.
View course details in MyPlan: IMT 558


IMT 559 Cybersecurity Functions and Trends (4)
Presents and analyzes cybersecurity technologies from a technical leadership stance to prepare information management professionals who will lead cybersecurity technical projects and information security teams. Introduces contemporary cybersecurity topics such as data analytics, digital forensic methodologies and cybersecurity applied in IoT (Internet of Things) and SDN (Software Defined Networks).
View course details in MyPlan: IMT 559


IMT 561 Data Visualization: Design and Development (4)
Introduction to human-centered design, development, and evaluation of data visualizations. Coursework focuses on techniques for designing and coding visualizations of structured data, including evaluating usability and accessibility. Topics include principles of visual perception; fundamentals of visual analytics; technical dimensions of visual encoding; prototyping; and usability testing.
View course details in MyPlan: IMT 561


IMT 563 Advanced Relational Database Management Systems (4)
Conducts deeper investigation into construction of high-volume, robust database systems from conception through deployment. Topics include Enhanced ERDs, explicit transaction-management (control-of-flow, error-handling), coded business rules, troubleshooting and optimization. Investigation of disaster recovery, security, high-availability and scalability solutions as well as NoSQL and data warehousing topics. Prerequisite: IMT 543 or LIS 543.
View course details in MyPlan: IMT 563


IMT 565 Designing Information Experiences (4)
Explores experience design including user experience, customer experience, and service design. Covers the philosophical foundations of experience, how to design and evaluate experiences, and the business aspects of customer experience. The focus is on experiences of and with information.
View course details in MyPlan: IMT 565


IMT 569 Capstone I: Project Preparation (1)
Preparation for implementing a capstone project. Topics include choosing a project, team formation, professional communication with a project sponsor, identifying the scope of the project, assessing feasibility, developing a project charter and sponsor agreement. Prerequisite: completion of all MSIM core courses. Credit/no-credit only.
View course details in MyPlan: IMT 569


IMT 570 Data Driven Organizational Problem Solving for Information Management Professionals (4)
Provides students with analytical skills and a systematic approach to solve complex problems related to information management in organizations. Using an applied project, students are introduced to problem solving methods and a variety of data gathering and analysis techniques, culminating in the development of effective, data driven, recommendations specific to information management, systems, and product development.
View course details in MyPlan: IMT 570


IMT 571 Social Network Analysis (4)
Provide students with an understanding of the fundamental concepts, common methods, and analytical tools of social network analysis. Student will gain experience applying both exploratory and inferential methods to real-world problems with in the social network domain.
View course details in MyPlan: IMT 571


IMT 572 Introduction to Data Science (4)
Introduces a broad, non-technical overview of key concepts, skills, and technologies used in "data science". Provides a high-level introduction to common data science pipelines, such as experimental design, data collection and storage, basic analytics, machine learning, and data visualization, focusing on analyzing in real-world datasets using industry standard statistical packages. Course equivalent to: LIS 572.
View course details in MyPlan: IMT 572


IMT 573 Data Science I: Theoretical Foundations (4)
Introduces technically focused theoretical foundations of "Data Science." Provides an overview of key concepts, focusing on foundational concepts such as exploratory data analysis and statistical inference. Assignments are data-intensive, and require significant programming and statistical analysis. Students are expected to have college-level statistics and programming experience (R and python preferred). Prerequisite: either QMETH 201, IMT 570, or equivalent college coursework; and either CSE 121, CSE 122, CSE 123, CSE 142, or equivalent college coursework.
View course details in MyPlan: IMT 573


IMT 574 Data Science II: Machine Learning (4)
Provides theoretical and practical introduction to modern techniques for the analysis of large-scale, heterogeneous data. Covers key concepts in inferential statistics, supervised and unsupervised machine learning, and network analysis. Students learn functional, procedural, and statistical programming techniques for working with real-world data. Prerequisite: IMT 573.
View course details in MyPlan: IMT 574


IMT 575 Data Science III: Scaling, Applications, and Ethics (4)
Challenges and opportunities of data science at massive scale. Covers systems and languages for manipulating data across hundreds of computers, tools and techniques for building large-scale neural models for text and images, and the impact on privacy and equity as these large-scale models proliferate. Prerequisite: IMT 574.
View course details in MyPlan: IMT 575


IMT 576 Foundations of Strategic and Managerial Business Intelligence (4)
Provides a broad overview of business intelligence (BI) including foundational BI concepts, strategies, techniques, and technologies. Primary emphasis is on the strategic and managerial perspective, focusing on how one designs, implements, and leverages business intelligence systems and strategies in management and leadership roles.
View course details in MyPlan: IMT 576


IMT 577 Business Intelligence Systems (4)
Introduces fundamentals of how to architect and develop business intelligence systems for decision making. Topics include dimensional data modeling; extracting, transforming, and loading data (ETL); online analytical processing (OLAP); data warehouse architecture; developing data visualizations to answer key business questions. Prerequisite: IMT 576; recommended: students are expected to have basic relational database and SQL knowledge. IMT 543 is recommended for students without this knowledge.
View course details in MyPlan: IMT 577


IMT 578 Research Seminar (1-4, max. 10)
Students work in teams under the supervision of individual faculty members to engage in research or design activities and learn through hands-on participation and study. Learning activities include data collection, data analysis, building prototypes, testing or evaluation, or dissemination activities. Course equivalent to: LIS 578.
View course details in MyPlan: IMT 578


IMT 579 People Analytics (4)
Introduces techniques used in people analytics to measure, analyze, make data-informed decisions, and build technology systems that leverage people data. Exposes students to the people analytics technology market and builds analytical thinking skills.
View course details in MyPlan: IMT 579


IMT 580 Management and Strategic Leadership (4)
Introduction to strategic leadership of information organizations. Examines key topics drawn from organizational theory and behavior, including planning and decision-making, organizational structure, leadership, and diversity and equity. Presents the opportunity to develop and broaden understanding of strategic and operational impact of technology on organizations and their management.
View course details in MyPlan: IMT 580


IMT 585 Program Management and Consulting (4)
Provides overview of skills, practices, and concepts foundational to a career in information management consulting. Topics include consulting concepts, methodologies, approaches to consultative analysis and problem solving, effective technical and interpersonal consulting behaviors, and program management in a consulting environment. Emphasizes interpersonal/communication skills, client relationship management, and change management. Prerequisite: IMT 580.
View course details in MyPlan: IMT 585


IMT 587 Principles of Information Project Management (4)
Introduces project management principles within information-related business contexts. Provides knowledge that managers need to implement information systems on time and within budget. Concentrates on methods and issues in organizing, planning, and controlling projects, and their use of computer-based project management tools.
View course details in MyPlan: IMT 587


IMT 590 Internship in Information Management (1-5, max. 10)
Internship in the private or public sector, jointly supervised by faculty member and an on-site work sponsor. Prerequisite: enrollment in the MSIM program. Credit/no-credit only.
View course details in MyPlan: IMT 590


IMT 596 Capstone II - Project Planning (2)
Analysis and preliminary design of an approved individual or group research or implementation project demonstrating professional-level knowledge and skills. Course overlaps with: LIS 596. Prerequisite: IMT 569. Credit/no-credit only.
View course details in MyPlan: IMT 596


IMT 597 Capstone III - Project Implementation (2)
Implementation of a project demonstrating professional-level knowledge and skills based on a project charter and plan developed in IMT 596. Course overlaps with: LIS 597. Prerequisite: IMT 596. Credit/no-credit only.
View course details in MyPlan: IMT 597


IMT 598 Special Topics in Information Management (1-4, max. 18)
Special study and research in topics of current concern to faculty and students.
View course details in MyPlan: IMT 598


IMT 599 Practicum in Information Management (6)
Internship,,organization- or faculty-sponsored research project related to information management.  Required for MSIM one-year students.  Usually offered summer quarter. Prerequisite: IMT 500; IMT 550; IMT 570; and IMT 580  Credit/no-credit only.
View course details in MyPlan: IMT 599


IMT 600 Independent Study or Research in Information Management ([1-4]-)
Supervised independent study or research. May be taken in as many as six consecutive quarters. Prerequisite: enrollment in the MSIM program. Credit/no-credit only.
View course details in MyPlan: IMT 600












Office of the University Registrar


registrar@uw.edu

Modified: April 15, 2026

In [ ]:
p_tags = soup.find_all("p")

print("how mant p tags:", len(p_tags))

for i, p in enumerate(p_tags[:10]):
    print(f"--- p tag {i} ---")
    print(p.get_text(" ", strip=True))
    print()

how mant p tags: 40
--- p tag 0 ---
Detailed course offerings (Time Schedule) are available for Spring Quarter 2026: Time Schedule (NetID required) | Course Offerings Summer Quarter 2026: Time Schedule (NetID required) | Course Offerings Autumn Quarter 2026: Time Schedule (NetID required) | Course Offerings

--- p tag 1 ---
IMT 500 Foundations of Information Management (4) Examines the role and function of information and information management in individual, organizational, community, and social contexts. Topics include defining information and information management concepts; overview of systems and systems architecture, methods of managing information and information flows within organizations; and internal and external communication in professional settings. View course details in MyPlan: IMT 500

--- p tag 2 ---
IMT 511 Introduction to Programming for Information and Data Science (4) Introduces fundamentals of computer programming as used for data science. Covers foundational skills necessary for writing stand-alone computer scripts, including programming syntax, data structuring, and procedural definition (functions). Includes programming tools and environments (e.g., command-line). Emphasizes skills in language syntax, debugging, algorithmic thinking, and data comprehension. Assumes no previous programming background. Course equivalent to: LIS 511. View course details in MyPlan: IMT 511

--- p tag 3 ---
IMT 519 Information Science Study Abroad (1-8, max. 18) International seminar, led by Information School faculty or researchers. Each addresses a specialized area of information studies. Topics vary. Some seminars may require language proficiency. See the UW Study Abroad website for information on specific offerings in any given year. Course equivalent to: LIS 519. View course details in MyPlan: IMT 519

--- p tag 4 ---
IMT 526 Building and Applying Large Language Models (4) Introduces the building blocks of large language models (LLMs) using theories and practice. Primarily covers foundational models and technical elements of LLMs through hands-on exercises and problems, while also covering the potential social impacts of particular technical decisions and approaches. Prerequisite: IMT 573 and IMT 574. View course details in MyPlan: IMT 526

--- p tag 5 ---
IMT 530 Organization of Information Resources (4) Introduction to issues in organization of information and information objects including analysis of intellectual and physical characteristics of information objects; use of metadata and metadata standards for information systems; theory of classification, including semantic relationships and facet analysis; creation of controlled vocabularies; and display and arrangement. View course details in MyPlan: IMT 530

--- p tag 6 ---
IMT 535 Introduction to Information Architecture (5) Introduces concepts and methods of front- and back-end information architecture. Covers back-end topics including data and content modeling, taxonomy, controlled vocabulary, SEO, search, and analytics. Covers front-end topics including design thinking, design process, design patterns, navigation, workflow, labeling, orientation, and information scent. Unifies front- and back-end IA. View course details in MyPlan: IMT 535

--- p tag 7 ---
IMT 540 Design Methods for Interactive Systems (4) Introduction to the theory and practice of user-centered design. Examines design methods for identifying and describing user needs, specifying and prototyping new systems, and evaluating the usability of systems. Examines design methodologies such as contextual design and value-sensitive design, giving specific emphasis to human-information interaction. Prerequisite: permission of instructor. View course details in MyPlan: IMT 540

--- p tag 8 ---
IMT 541 Enterprise Information Systems Analysis and Design (4) Uses Systems Development Lifecycle (SDLC) as a methodology for addressing complex enterprise information systems problems. Through each phase of SDLC, students engage in current and future state analysis and design activities, including, project identification, selection and initiation, baseline project planning, feasibility and risk analysis, requirements gathering and structuring, system development, implementation, and maintenance strategies. View course details in MyPlan: IMT 541

--- p tag 9 ---
IMT 542 Portable Information Structures (4) Introduces the concepts and methods used to analyze, store, manage, and present information and navigation. Equal weight given to understanding structures and implementing them. Topics covered include information analysis and organizational methods as well as markup standards (e.g., JSON, XML) and metadata concepts and application. View course details in MyPlan: IMT 542

In [ ]:
sample = p_tags[1].get_text(" ", strip=True)
print(sample)

IMT 500 Foundations of Information Management (4) Examines the role and function of information and information management in individual, organizational, community, and social contexts. Topics include defining information and information management concepts; overview of systems and systems architecture, methods of managing information and information flows within organizations; and internal and external communication in professional settings. View course details in MyPlan: IMT 500

In [ ]:
cleaned = sample.split("View course details in MyPlan:")[0].strip()
print(cleaned)

IMT 500 Foundations of Information Management (4) Examines the role and function of information and information management in individual, organizational, community, and social contexts. Topics include defining information and information management concepts; overview of systems and systems architecture, methods of managing information and information flows within organizations; and internal and external communication in professional settings.

In [ ]:
import re

match = re.match(r"^(IMT\s+\d+)\s+(.+?)\s+\((\d+)\)\s+(.*)$", cleaned)

if match:
    course_id = match.group(1)
    course_title = match.group(2)
    credits = match.group(3)
    description = match.group(4)

    print("course_id:", course_id)
    print("course_title:", course_title)
    print("credits:", credits)
    print("description:", description)
else:
    print("No match found")

course_id: IMT 500
course_title: Foundations of Information Management
credits: 4
description: Examines the role and function of information and information management in individual, organizational, community, and social contexts. Topics include defining information and information management concepts; overview of systems and systems architecture, methods of managing information and information flows within organizations; and internal and external communication in professional settings.

In [ ]:
b_tags = soup.find_all("b")

titles = []
for b in b_tags:
    text = b.get_text(" ", strip=True)
    if text.startswith("IMT "):
        titles.append(text)

print("how many titles:", len(titles))
for t in titles[:10]:
    print(t)

how many titles: 39
IMT 500 Foundations of Information Management (4)
IMT 511 Introduction to Programming for Information and Data Science (4)
IMT 519 Information Science Study Abroad (1-8, max. 18)
IMT 526 Building and Applying Large Language Models (4)
IMT 530 Organization of Information Resources (4)
IMT 535 Introduction to Information Architecture (5)
IMT 540 Design Methods for Interactive Systems (4)
IMT 541 Enterprise Information Systems Analysis and Design (4)
IMT 542 Portable Information Structures (4)
IMT 543 Relational Database Management Systems (4)

In [ ]:
import re
import pandas as pd

rows = []

for b in b_tags:
    title_text = b.get_text(" ", strip=True)

    if not title_text.startswith("IMT "):
        continue

    match = re.match(r"^(IMT\s+\d+)\s+(.+?)\s+\((.*?)\)$", title_text)
    if not match:
        continue

    course_id = match.group(1)
    course_title = match.group(2)
    credits = match.group(3)

    description = ""

    for p in p_tags:
        p_text = p.get_text(" ", strip=True)
        if title_text in p_text:
            description = p_text.replace(title_text, "").split("View course details in MyPlan:")[0].strip()
            break

    rows.append({
        "course_id": course_id,
        "course_title": course_title,
        "credits": credits,
        "description": description
    })

df = pd.DataFrame(rows)
print(df.shape)
df

(39, 4)

,course_id,course_title,credits,description
0,IMT 500,Foundations of Information Management,4,Examines the role and function of information ...
1,IMT 511,Introduction to Programming for Information an...,4,Introduces fundamentals of computer programmin...
2,IMT 519,Information Science Study Abroad,"1-8, max. 18","International seminar, led by Information Scho..."
3,IMT 526,Building and Applying Large Language Models,4,Introduces the building blocks of large langua...
4,IMT 530,Organization of Information Resources,4,Introduction to issues in organization of info...
5,IMT 535,Introduction to Information Architecture,5,Introduces concepts and methods of front- and ...
6,IMT 540,Design Methods for Interactive Systems,4,Introduction to the theory and practice of use...
7,IMT 541,Enterprise Information Systems Analysis and De...,4,Uses Systems Development Lifecycle (SDLC) as a...
8,IMT 542,Portable Information Structures,4,Introduces the concepts and methods used to an...
9,IMT 543,Relational Database Management Systems,4,"Introduces relational database design, impleme..."
10,IMT 546,Data Communications and Networking,4,Covers local and wide-area computer networking...
11,IMT 547,Social Media Data Mining and Analysis,4,Explores techniques for collecting and analyzi...
12,IMT 550,Policy and Ethics in Information Management,4,Explores a range of information issues in the ...
13,IMT 555,Foundations of Cybersecurity,4,Examines information security challenges and s...
14,IMT 558,Leading and Managing Enterprise Information Se...,4,Examines the elements of managing and leading ...
15,IMT 559,Cybersecurity Functions and Trends,4,Presents and analyzes cybersecurity technologi...
16,IMT 561,Data Visualization: Design and Development,4,"Introduction to human-centered design, develop..."
17,IMT 563,Advanced Relational Database Management Systems,4,Conducts deeper investigation into constructio...
18,IMT 565,Designing Information Experiences,4,Explores experience design including user expe...
19,IMT 569,Capstone I: Project Preparation,1,Preparation for implementing a capstone projec...
20,IMT 570,Data Driven Organizational Problem Solving for...,4,Provides students with analytical skills and a...
21,IMT 571,Social Network Analysis,4,Provide students with an understanding of the ...
22,IMT 572,Introduction to Data Science,4,"Introduces a broad, non-technical overview of ..."
23,IMT 573,Data Science I: Theoretical Foundations,4,Introduces technically focused theoretical fou...
24,IMT 574,Data Science II: Machine Learning,4,Provides theoretical and practical introductio...
25,IMT 575,"Data Science III: Scaling, Applications, and E...",4,Challenges and opportunities of data science a...
26,IMT 576,Foundations of Strategic and Managerial Busine...,4,Provides a broad overview of business intellig...
27,IMT 577,Business Intelligence Systems,4,Introduces fundamentals of how to architect an...
28,IMT 578,Research Seminar,"1-4, max. 10",Students work in teams under the supervision o...
29,IMT 579,People Analytics,4,Introduces techniques used in people analytics...
30,IMT 580,Management and Strategic Leadership,4,Introduction to strategic leadership of inform...
31,IMT 585,Program Management and Consulting,4,"Provides overview of skills, practices, and co..."
32,IMT 587,Principles of Information Project Management,4,Introduces project management principles withi...
33,IMT 590,Internship in Information Management,"1-5, max. 10","Internship in the private or public sector, jo..."
34,IMT 596,Capstone II - Project Planning,2,Analysis and preliminary design of an approved...
35,IMT 597,Capstone III - Project Implementation,2,Implementation of a project demonstrating prof...
36,IMT 598,Special Topics in Information Management,"1-4, max. 18",Special study and research in topics of curren...
37,IMT 599,Practicum in Information Management,6,"Internship,,organization- or faculty-sponsored..."
38,IMT 600,Independent Study or Research in Information M...,[1-4]-,Supervised independent study or research. May ...

In [ ]:
tag_map = {
    "IMT 526": {
        "career_path_tags": "AI",
        "skill_tags": "llm;foundation models;prompting;applied ai;model evaluation"
    },
    "IMT 530": {
        "career_path_tags": "IA",
        "skill_tags": "metadata;classification;controlled vocabulary;information organization;taxonomy"
    },
    "IMT 535": {
        "career_path_tags": "IA",
        "skill_tags": "information architecture;content modeling;navigation;labeling;taxonomy;seo"
    },
    "IMT 540": {
        "career_path_tags": "UX",
        "skill_tags": "user-centered design;design research;prototyping;interaction design;user needs"
    },
    "IMT 541": {
        "career_path_tags": "PPMC",
        "skill_tags": "systems analysis;enterprise systems;requirements;process design;solution design"
    },
    "IMT 542": {
        "career_path_tags": "IA",
        "skill_tags": "information structures;navigation;content structure;portability;information design"
    },
    "IMT 555": {
        "career_path_tags": "InfoSec",
        "skill_tags": "cybersecurity;risk;security fundamentals;threats;security strategy"
    },
    "IMT 558": {
        "career_path_tags": "InfoSec",
        "skill_tags": "security leadership;governance;risk management;compliance;security program management"
    },
    "IMT 559": {
        "career_path_tags": "InfoSec",
        "skill_tags": "cybersecurity trends;security technologies;technical leadership;risk analysis"
    },
    "IMT 561": {
        "career_path_tags": "UX",
        "skill_tags": "data visualization;visual design;human-centered design;coding;data storytelling"
    },
    "IMT 565": {
        "career_path_tags": "UX",
        "skill_tags": "experience design;ux;service design;customer experience;design strategy"
    },
    "IMT 572": {
        "career_path_tags": "BI",
        "skill_tags": "data science fundamentals;data literacy;analytics;data workflows;applied data"
    },
    "IMT 573": {
        "career_path_tags": "DS",
        "skill_tags": "data science;statistics;modeling;technical foundations;data analysis"
    },
    "IMT 574": {
        "career_path_tags": "DS",
        "skill_tags": "machine learning;predictive modeling;data analysis;model evaluation"
    },
    "IMT 575": {
        "career_path_tags": "DS",
        "skill_tags": "scaling data science;big data;ethics;data systems;applications"
    },
    "IMT 576": {
        "career_path_tags": "BI",
        "skill_tags": "business intelligence;decision making;analytics strategy;dashboards;reporting"
    },
    "IMT 577": {
        "career_path_tags": "BI",
        "skill_tags": "bi systems;etl;data warehousing;dimensional modeling;decision support"
    },
    "IMT 585": {
        "career_path_tags": "PPMC",
        "skill_tags": "consulting;program management;stakeholder management;business problem solving"
    },
    "IMT 587": {
        "career_path_tags": "PPMC",
        "skill_tags": "project management;planning;execution;stakeholder communication;business context"
    }
}

In [ ]:
tag_map.update({
    "IMT 500": {
        "career_path_tags": "General",
        "skill_tags": "information management;systems thinking;professional communication;organizational context"
    },
    "IMT 511": {
        "career_path_tags": "General;DS;AI",
        "skill_tags": "python;programming;data structures;debugging;computational thinking"
    },
    "IMT 543": {
        "career_path_tags": "DS;BI",
        "skill_tags": "sql;database design;relational databases;data management"
    },
    "IMT 547": {
        "career_path_tags": "DS;BI",
        "skill_tags": "social media analysis;data collection;text analysis;applied analytics"
    },
    "IMT 550": {
        "career_path_tags": "General",
        "skill_tags": "ethics;policy;privacy;information governance"
    },
    "IMT 571": {
        "career_path_tags": "DS",
        "skill_tags": "social network analysis;graph analysis;network methods;data interpretation"
    },
    "IMT 579": {
        "career_path_tags": "BI;PPMC",
        "skill_tags": "people analytics;measurement;decision making;organizational data"
    },
    "IMT 580": {
        "career_path_tags": "PPMC",
        "skill_tags": "leadership;strategy;organizational behavior;management"
    }
})

In [ ]:
df["career_path_tags"] = df["course_id"].map(lambda x: tag_map.get(x, {}).get("career_path_tags", ""))
df["skill_tags"] = df["course_id"].map(lambda x: tag_map.get(x, {}).get("skill_tags", ""))

In [ ]:
df[["course_id", "career_path_tags", "skill_tags"]].head(10)

,course_id,career_path_tags,skill_tags
0,IMT 500,General,information management;systems thinking;profes...
1,IMT 511,General;DS;AI,python;programming;data structures;debugging;c...
2,IMT 519,,
3,IMT 526,AI,llm;foundation models;prompting;applied ai;mod...
4,IMT 530,IA,metadata;classification;controlled vocabulary;...
5,IMT 535,IA,information architecture;content modeling;navi...
6,IMT 540,UX,user-centered design;design research;prototypi...
7,IMT 541,PPMC,systems analysis;enterprise systems;requiremen...
8,IMT 542,IA,information structures;navigation;content stru...
9,IMT 543,DS;BI,sql;database design;relational databases;data ...

In [ ]:
import pandas as pd

def recommend_courses(df, keyword):
    keyword = keyword.lower().strip()
    results = []

    for _, row in df.iterrows():
        score = 0

        course_title = str(row.get("course_title", "")).lower()
        description = str(row.get("description", "")).lower()
        career_path_tags = str(row.get("career_path_tags", "")).lower()
        skill_tags = str(row.get("skill_tags", "")).lower()

        if keyword in course_title:
            score += 3
        if keyword in career_path_tags:
            score += 4
        if keyword in skill_tags:
            score += 3
        if keyword in description:
            score += 1

        if score > 0:
            results.append({
                "course_id": row["course_id"],
                "course_title": row["course_title"],
                "credits": row["credits"],
                "career_path_tags": row["career_path_tags"],
                "skill_tags": row["skill_tags"],
                "score": score
            })

    if results:
        return pd.DataFrame(results).sort_values(by=["score", "course_id"], ascending=[False, True])
    else:
        return pd.DataFrame(columns=[
            "course_id", "course_title", "credits",
            "career_path_tags", "skill_tags", "score"
        ])

In [ ]:
keyword = input("Enter a career path or skill keyword: ")
recommend_courses(df, keyword)

Enter a career path or skill keyword: UX

,course_id,course_title,credits,career_path_tags,skill_tags,score
2,IMT 565,Designing Information Experiences,4,UX,experience design;ux;service design;customer e...,7
0,IMT 540,Design Methods for Interactive Systems,4,UX,user-centered design;design research;prototypi...,4
1,IMT 561,Data Visualization: Design and Development,4,UX,data visualization;visual design;human-centere...,4